"""career-ops skill launchpad: capability detection + a registry of skills a
triaged role can launch.

Each skill runs one of two ways, chosen by the user per action (unless they set
SKILL_PATH_DEFAULT):

  - **API path** — a synchronous provider call that reuses
    ``pipeline.batch_evaluate``'s provider plumbing. Bounded, non-interactive,
    needs only an API key (no agent CLI installed).
  - **CLI path** — we build a ready-to-run command for the user's agent CLI and
    hand it off. We never spawn a tool-wielding agent from this web server.

Only skills whose work fits a single bounded text call expose the API path.
Résumé-markdown tailoring does; **PDF** (needs Playwright to render),
**interview-prep** (needs live WebSearch) and **apply** (needs a live browser)
are CLI-only — the agent does what an API call can't.

Skills read ``cv.md`` + ``config/profile.yml`` from the **local** career-ops
install (the source of truth — these are not in a downloaded artifact) and use
the role's evaluation **report** as the JD signal.
"""

import os
import re
import shlex
import shutil
import subprocess
import sys
import tempfile
from datetime import date
from pathlib import Path

from pipeline import batch_evaluate as be


class SkillError(RuntimeError):
    """A skill couldn't run for a reason worth surfacing to the user."""


# ── Capability detection ─────────────────────────────────────────────────────

def cli_name() -> str:
    """The agent CLI the CLI path would hand off to (BATCH_CLI, default claude)."""
    return (os.environ.get("BATCH_CLI") or "").strip() or "claude"


def cli_available() -> bool:
    return shutil.which(cli_name()) is not None


def detect_provider() -> str | None:
    """The provider the API path would use, or None if no usable key is set.

    Reuses batch_evaluate's detection + validation so the UI and
    ``--evaluate-batch`` always agree on which provider is active."""
    provider = be._detect_provider()
    if not provider:
        return None
    # BATCH_PROVIDER may name a provider whose key isn't actually present.
    return None if be._check_provider(provider) else provider


def default_path() -> str:
    """Preferred path when both are available: 'ask' (let the user pick),
    'cli', or 'api'. Anything unrecognized falls back to 'ask'."""
    v = (os.environ.get("SKILL_PATH_DEFAULT") or "ask").strip().lower()
    return v if v in ("ask", "cli", "api") else "ask"


# ── "Run in terminal" (one-click launch of the CLI hand-off command) ─────────
# This is *not* the agent running inside the web server — we spawn a new
# visible console window from which the user's agent runs. They see what's
# executing, can read its output, and can kill it; we never have a
# tool-wielding agent as a child of the FastAPI process.

# Linux terminal emulators we know how to launch, in preference order. We pick
# the first one on PATH. `flag` is what each emulator uses to mean "run this
# program" — gnome-terminal switched to `--`, kitty wants no flag, the rest
# settle on `-e`.
_LINUX_TERMINALS = [
    # (binary, flag-list-prefix)
    ("x-terminal-emulator", ["-e"]),  # Debian/Ubuntu's user-preferred selector
    ("gnome-terminal", ["--"]),
    ("konsole", ["-e"]),
    ("xfce4-terminal", ["-e"]),
    ("alacritty", ["-e"]),
    ("kitty", []),
    ("wezterm", ["start", "--"]),
    ("tilix", ["-e"]),
    ("terminator", ["-e"]),
    ("xterm", ["-e"]),  # universal fallback
]


def _resolve_linux_terminal() -> tuple[str, list[str]] | None:
    """Pick a usable terminal emulator on Linux. `$TERMINAL` (user override)
    wins; otherwise the first emulator from _LINUX_TERMINALS on PATH."""
    env = (os.environ.get("TERMINAL") or "").strip()
    if env and shutil.which(env):
        # The user told us which one; assume the common `-e` convention.
        return env, ["-e"]
    for name, flags in _LINUX_TERMINALS:
        if shutil.which(name):
            return name, flags
    return None


def terminal_available() -> bool:
    """Whether we can launch a visible terminal on this OS. Windows: always
    (cmd is present). macOS: always (Terminal.app is present). Linux: only if
    we find a known terminal emulator on PATH (or one named by `$TERMINAL`)."""
    if os.name == "nt":
        return True
    if sys.platform == "darwin":
        return True
    if sys.platform.startswith("linux"):
        return _resolve_linux_terminal() is not None
    return False


def _write_unix_script(command: str, cwd: str) -> str:
    """Write a portable shell wrapper that cd's into cwd, runs the command,
    then waits for a keypress so the user can read the agent's output. Marked
    executable so the OS can launch it directly."""
    script = (
        "#!/usr/bin/env bash\n"
        "# Generated by the job-search-pipeline UI. Safe to delete.\n"
        f"cd {shlex.quote(cwd)} || exit 1\n"
        f"{command}\n"
        "echo\n"
        'echo "(Done — press any key to close.)"\n'
        "read -n 1 -s\n"
    )
    tf = tempfile.NamedTemporaryFile(
        mode="w", suffix=".sh", delete=False, encoding="utf-8",
    )
    tf.write(script)
    tf.close()
    os.chmod(tf.name, 0o755)
    return tf.name


def _launch_windows(command: str, cwd: str) -> dict:
    """Windows: a .cmd wrapper run via CREATE_NEW_CONSOLE so it pops a new
    visible window. UTF-8 codepage so accented role/company names render."""
    script = (
        "@echo off\r\n"
        "chcp 65001 >nul\r\n"
        f"{command}\r\n"
        "echo.\r\n"
        "echo (You can close this window when done.)\r\n"
        "pause >nul\r\n"
    )
    tf = tempfile.NamedTemporaryFile(
        mode="w", suffix=".cmd", delete=False, encoding="utf-8",
    )
    tf.write(script)
    tf.close()
    # CREATE_NEW_CONSOLE = 0x10. We deliberately don't unlink the script —
    # the child needs it alive to run, and Windows cleans %TEMP% over time.
    subprocess.Popen(
        [tf.name], cwd=cwd, creationflags=0x10, close_fds=True,
    )
    return {"launcher": "cmd", "script": tf.name}


def _launch_macos(command: str, cwd: str) -> dict:
    """macOS: `open -a Terminal <script>` opens the .command script in
    Terminal.app, which runs it in a new window. The script's `read` keeps
    the window open until the user presses a key."""
    script_path = _write_unix_script(command, cwd)
    subprocess.Popen(["open", "-a", "Terminal", script_path], close_fds=True)
    return {"launcher": "Terminal.app", "script": script_path}


def _launch_linux(command: str, cwd: str) -> dict:
    """Linux: find a terminal emulator, then invoke `<term> [flags] <script>`.
    Each emulator's per-program-launch flag differs (gnome-terminal uses `--`,
    kitty takes no flag, most others take `-e`) — handled in _LINUX_TERMINALS."""
    chosen = _resolve_linux_terminal()
    if chosen is None:
        raise SkillError(
            "Couldn't find a terminal emulator on PATH. Install one (e.g. "
            "gnome-terminal, konsole, xterm) or set $TERMINAL to your preferred "
            "emulator, then reload. Or use Copy command and run it manually."
        )
    term, flags = chosen
    script_path = _write_unix_script(command, cwd)
    subprocess.Popen([term, *flags, script_path], close_fds=True)
    return {"launcher": term, "script": script_path}


def launch_in_terminal(command: str, cwd: str) -> dict:
    """Open a new console window and run `command` from `cwd`. The window stays
    open after the command exits so the user can read agent output (it's a
    new top-level window — they close it when done).

    Returns a small dict describing what was launched, for the UI to show."""
    if os.name == "nt":
        return _launch_windows(command, cwd)
    if sys.platform == "darwin":
        return _launch_macos(command, cwd)
    if sys.platform.startswith("linux"):
        return _launch_linux(command, cwd)
    raise SkillError(
        f"Run-in-terminal isn't wired up for this OS ({sys.platform}). "
        "Use Copy command and run it in your own terminal."
    )


# ── Skill registry ───────────────────────────────────────────────────────────
# Each skill maps to a career-ops mode. `api=True` means the work fits a single
# bounded provider call (we implement a runner below); otherwise it's CLI-only
# because it needs agent tools (browser, live web). `verb` fills the hand-off
# prompt. `prereqs` is a list of short one-line setup notes — surfaced inline
# in the UI whenever a CLI hand-off is generated, so users see the requirement
# right at the point of use instead of buried in docs.
_PLAYWRIGHT_MCP_NOTE = (
    "Needs the Playwright MCP server registered with your agent (one-time):  "
    "`claude mcp add playwright -- npx -y @playwright/mcp@latest`"
)
_CHROMIUM_NOTE = (
    "Needs Chromium installed for Playwright (one-time, in career-ops/):  "
    "`npx playwright install chromium`"
)

SKILLS: dict[str, dict] = {
    "tailor-resume": {
        "label": "Tailor résumé (Markdown)",
        "mode": "text",
        "verb": "tailor my résumé (markdown output)",
        "api": True,
        "prereqs": [],
    },
    "tailor-resume-pdf": {
        "label": "Tailor résumé (PDF)",
        "mode": "pdf",
        "verb": "generate a tailored ATS-optimized PDF résumé",
        "api": False,  # PDF rendering needs the agent (Playwright)
        "prereqs": [_CHROMIUM_NOTE],
    },
    "interview-prep": {
        "label": "Interview prep",
        "mode": "interview-prep",
        "verb": "prep me for an interview",
        "api": False,  # needs live WebSearch research
        "prereqs": [],
    },
    "apply": {
        "label": "Apply assistant",
        "mode": "apply",
        "verb": "help me fill out the application",
        "api": False,  # needs a live browser via the Playwright MCP server
        "prereqs": [_PLAYWRIGHT_MCP_NOTE, _CHROMIUM_NOTE],
    },
}


def capabilities() -> dict:
    provider = detect_provider()
    return {
        "cli": {"available": cli_available(), "name": cli_name()},
        "api": {"available": provider is not None, "provider": provider},
        "terminal": {"available": terminal_available()},
        "default_path": default_path(),
        "skills": [
            {
                "id": sid,
                "label": s["label"],
                "api": s["api"],
                "prereqs": s.get("prereqs", []),
            }
            for sid, s in SKILLS.items()
        ],
    }


def skill_command(skill_id: str, report_path: Path | None,
                  company: str, role: str) -> str:
    """Build the CLI hand-off command for any skill. We never spawn it — the
    user runs it in their terminal where the agent's tools/cost are visible.

    The command `cd`s into career-ops (the UI is launched from the repo root, so
    the relative path is fine) and points at the role's report by **absolute**
    path — the report may live in a downloaded-artifact cache (after a Refresh),
    not under career-ops/reports/, so a career-ops-relative path would miss it.
    Forward slashes work across PowerShell, cmd, and bash."""
    s = SKILLS[skill_id]
    prompt = f"use {s['mode']} mode to {s['verb']} for {company} / {role}"
    if report_path is not None:
        prompt += f" (evaluation report: {report_path.resolve().as_posix()})"
    return f'cd career-ops && {cli_name()} "{prompt}"'


# ── Résumé tailoring (the one API-path skill) ────────────────────────────────

def _slug(s: str) -> str:
    s = re.sub(r"[^\w\s-]", "", (s or "").lower())
    return re.sub(r"[\s_]+", "-", s).strip("-") or "x"


def _read(p: Path) -> str:
    try:
        return p.read_text(encoding="utf-8")
    except OSError:
        return ""


def _candidate_slug(local: Path) -> str:
    text = _read(local / "config" / "profile.yml")
    m = re.search(r"(?m)^\s*name:\s*[\"']?(.+?)[\"']?\s*$", text)
    return _slug(m.group(1)) if m else "candidate"


# Used only if the local career-ops modes/ aren't available (e.g. the UI was
# pointed at a bare artifact dir). The mode file is the authoritative source.
_FALLBACK_RULES = (
    "Generate a JD-tailored resume as markdown that mirrors the structure of the "
    "candidate's CV: same section headings, same order. Reorder and reword the "
    "candidate's REAL experience to surface JD-relevant content and inject JD "
    "keywords naturally. NEVER invent skills or experience beyond the CV. Output "
    "pure markdown — no tables, no HTML, no code fences."
)


def build_tailor_messages(local: Path, role_context: str) -> tuple[str, str]:
    """Build (system, user) messages for the API tailoring call. The mode rules
    come from the local ``modes/text.md`` so we don't duplicate them here."""
    cv = _read(local / "cv.md")
    if not cv.strip():
        raise SkillError(
            "cv.md not found in your local career-ops — run setup/onboarding "
            "first, or launch the UI from your career-ops clone."
        )
    profile = _read(local / "config" / "profile.yml")
    rules = _read(local / "modes" / "text.md").strip() or _FALLBACK_RULES
    system = (
        "You tailor resumes. Follow these mode rules exactly:\n\n"
        f"{rules}\n\n"
        "=== CANDIDATE CV (source of truth — never claim anything beyond it) ===\n"
        f"{cv}\n\n"
        "=== CANDIDATE PROFILE (identity / contact) ===\n"
        f"{profile}\n"
    )
    user = (
        "Tailor the resume for the role below. The text is the evaluation report "
        "for that role; use its Requirements Map and role summary as the JD "
        "signal.\n\n"
        f"{role_context}\n\n"
        "Output ONLY the tailored resume as markdown — no preamble, no code fences."
    )
    return system, user


def _strip_fences(text: str) -> str:
    text = text.strip()
    text = re.sub(r"^```(?:markdown|md)?\s*\n", "", text)
    text = re.sub(r"\n```\s*$", "", text)
    return text.strip()


def tailor_resume_markdown(
    local: Path, role_context: str, company: str, provider: str, model: str | None,
) -> Path:
    """Run the API tailoring path. Writes the tailored markdown to the local
    career-ops ``output/`` dir (matching modes/text.md's naming) and returns it."""
    system, user = build_tailor_messages(local, role_context)
    model = model or os.environ.get("BATCH_MODEL") or be.PROVIDER_DEFAULTS[provider]
    caller = be._build_caller(provider, model)
    content = _strip_fences(be._call_with_retry(caller, system, user))
    if not content:
        raise SkillError("The provider returned an empty resume.")
    out = (local / "output" /
           f"cv-{_candidate_slug(local)}-{_slug(company)}-{date.today().isoformat()}.md")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content + "\n", encoding="utf-8")
    return out
